//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

//------------------------------------------------------------------------------

namespace Xyz.Xrm.Entities
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.42")]
	public enum and_SalesCycleCode1
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("ADDC", 0, "#0000ff", "Add Channel")]
		ADDC = 118790000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("DOUBLE", 1, "#0000ff", "Double Play")]
		DOUBLE = 118790001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("HD UPGRADE", 2, "#0000ff", "HD Upgrade")]
		HDUPGRADE = 118790002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("INTERNET", 3, "#0000ff", "Internet Install")]
		INTERNET = 118790003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("NEWHD", 5, "#0000ff", "New HD Installation")]
		NEWHD = 118790005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("NEW OTT", 4, "#0000ff", "New OTT Install")]
		NEWOTT = 118790004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("NEWOVR", 6, "#0000ff", "New Overlay Install")]
		NEWOVR = 118790006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("OTTUP", 7, "#0000ff", "OTT Upgrade")]
		OTTUP = 118790007,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("ROOMS", 8, "#0000ff", "Room Count Change")]
		ROOMS = 118790008,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("SALVAGE", 9, "#0000ff", "Salvage")]
		SALVAGE = 118790009,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("TRIPLE", 10, "#0000ff", "Triple Play")]
		TRIPLE = 118790010,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("VOICE", 11, "#0000ff", "Voice Install")]
		VOICE = 118790011,
	}
}