#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xyz.Xrm.Entities
{
	
	
	/// <summary>
	/// Shows the different options for online meetings.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum OnlineMeetingType
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Teams Meeting", 0)]
		TeamsMeeting = 1,
	}
}
#pragma warning restore CS1591
