//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

//------------------------------------------------------------------------------

namespace Xyz.Xrm.Entities
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.42")]
	public enum QueueItem_ObjectTypeCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Activity", 20, null, "Task performed, or to be performed, by a user. An activity is any action for whic" +
			"h an entry can be made on a calendar.")]
		Activity = 4200,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Agreement Booking Date", 4, null, "Specify the maintenance booking dates for the agreement.")]
		AgreementBookingDate = 10105,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Agreement Booking Setup", 5, null, "Specify the maintenance bookings for the agreement.")]
		AgreementBookingSetup = 10110,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Agreement Invoice Date", 30, null, "Specify the invoice dates for the agreement.")]
		AgreementInvoiceDate = 10111,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Agreement Invoice Setup", 31, null, "Specify the invoices for this agreement.")]
		AgreementInvoiceSetup = 10113,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Appointment", 24, null, "Commitment representing a time interval with start/end times and duration.")]
		Appointment = 4201,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Approval", 32, null, "Container for approvals.")]
		Approval = 10029,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Booking Alert", 1, null, "Alerts that notify schedule board users of booking issues or information.")]
		BookingAlert = 10006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Campaign Activity", 10, null, "Task performed, or to be performed, by a user for planning or running a campaign." +
			"")]
		CampaignActivity = 4402,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Campaign Response", 13, null, "Response from an existing or a potential new customer for a campaign.")]
		CampaignResponse = 4401,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Case", 14, null, "Service request case associated with a contract.")]
		Case = 112,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Email", 28, null, "Activity that is delivered using email protocols.")]
		Email = 4202,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Fax", 25, null, "Activity that tracks call outcome and number of pages for a fax and optionally st" +
			"ores an electronic copy of the document.")]
		Fax = 4204,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Forms Pro survey invite", 6, null, "Activity that tracks a survey invitation sent to a person.")]
		FormsProsurveyinvite = 10241,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Forms Pro survey response", 0, null, "Response to a survey.")]
		FormsProsurveyresponse = 10242,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("inMail", 15, null, "Custom Activity entity to store LinkedIn inMail records.")]
		inMail = 10247,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Inventory Adjustment", 3, null, "Records inventory adjustments")]
		InventoryAdjustment = 10130,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Inventory Transfer", 29, null, "Records inventory adjustments")]
		InventoryTransfer = 10133,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Knowledge Article", 26, null, "Organizational knowledge for internal and external use.")]
		KnowledgeArticle = 9953,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Knowledge Article Template", 12, null, "Organizational Knowledge Article Template for Internal and external creation of K" +
			"nowledge Articles.")]
		KnowledgeArticleTemplate = 10275,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Letter", 23, null, "Activity that tracks the delivery of a letter. The activity can contain the elect" +
			"ronic copy of the letter.")]
		Letter = 4207,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Message", 7, null, "Custom Activity entity to store LinkedIn Message records.")]
		Message = 10248,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Phone Call", 22, null, "Activity to track a telephone call.")]
		PhoneCall = 4210,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("PointDrive Presentation Viewed", 18, null, "Custom Activity entity to store PointDrive Presentation Viewed records.")]
		PointDrivePresentationViewed = 10249,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Project", 9, null, "Delivery entity in an engagement.")]
		Project = 10064,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Project Task", 34, null, "Tasks related to project.")]
		ProjectTask = 10069,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Quick Campaign", 11, null, "System operation used to perform lengthy and asynchronous operations on large dat" +
			"a sets, such as distributing a campaign activity or quick campaign.")]
		QuickCampaign = 4406,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Recurring Appointment", 19, null, "The Master appointment of a recurring appointment series.")]
		RecurringAppointment = 4251,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Resource Request", 33, null, "Entity that wraps the resource requirement to capture the type of resources, skil" +
			"ls, and location required.")]
		ResourceRequest = 10086,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Service Activity", 17, null, "Activity offered by the organization to satisfy its customer\'s needs. Each servic" +
			"e activity includes date, time, duration, and required resources.")]
		ServiceActivity = 4214,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Social Activity", 27, null, "For internal use only.")]
		SocialActivity = 4216,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Task", 21, null, "Generic activity representing work needed to be done.")]
		Task = 4212,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Time Group", 37, null, "Specify time groups consisting of multiple time windows to be used for scheduling" +
			", for example.")]
		TimeGroup = 10024,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Time Group Detail", 16, null, "Specify individual time windows under a time group.")]
		TimeGroupDetail = 10025,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Work Order", 8, null, "Work orders store all information about the job performed for an account. Stores " +
			"incident details, resource, expenses, tasks, communications, billing and more")]
		WorkOrder = 10173,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Work Order Incident", 35, null, "Specify work order incidents reported to you by the client. These are also referr" +
			"ed to as problem codes.")]
		WorkOrderIncident = 10176,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Work Order Service", 36, null, "Record all services proposed and performed for work order")]
		WorkOrderService = 10179,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Work Order Service Task", 2, null, "Store service tasks that are to be performed for this work order")]
		WorkOrderServiceTask = 10180,
	}
}