#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Microsoft.Xrm.Sdk.Client.ProxyTypesAssemblyAttribute()]

namespace Xyz.Xrm.Entities
{
	
	
	/// <summary>
	/// Represents a source of entities bound to a Dataverse service. It tracks and manages changes made to the retrieved entities.
	/// </summary>
	public partial class DataverseContext : Microsoft.Xrm.Sdk.Client.OrganizationServiceContext
	{
		
		/// <summary>
		/// Constructor.
		/// </summary>
		public DataverseContext(Microsoft.Xrm.Sdk.IOrganizationService service) : 
				base(service)
		{
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Xyz.Xrm.Entities.Account"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Xyz.Xrm.Entities.Account> AccountSet
		{
			get
			{
				return this.CreateQuery<Xyz.Xrm.Entities.Account>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Xyz.Xrm.Entities.ActivityMimeAttachment"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Xyz.Xrm.Entities.ActivityMimeAttachment> ActivityMimeAttachmentSet
		{
			get
			{
				return this.CreateQuery<Xyz.Xrm.Entities.ActivityMimeAttachment>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Xyz.Xrm.Entities.ActivityParty"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Xyz.Xrm.Entities.ActivityParty> ActivityPartySet
		{
			get
			{
				return this.CreateQuery<Xyz.Xrm.Entities.ActivityParty>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Xyz.Xrm.Entities.ActivityPointer"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Xyz.Xrm.Entities.ActivityPointer> ActivityPointerSet
		{
			get
			{
				return this.CreateQuery<Xyz.Xrm.Entities.ActivityPointer>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Xyz.Xrm.Entities.Annotation"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Xyz.Xrm.Entities.Annotation> AnnotationSet
		{
			get
			{
				return this.CreateQuery<Xyz.Xrm.Entities.Annotation>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Xyz.Xrm.Entities.AppConfig"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Xyz.Xrm.Entities.AppConfig> AppConfigSet
		{
			get
			{
				return this.CreateQuery<Xyz.Xrm.Entities.AppConfig>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Xyz.Xrm.Entities.AppConfigInstance"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Xyz.Xrm.Entities.AppConfigInstance> AppConfigInstanceSet
		{
			get
			{
				return this.CreateQuery<Xyz.Xrm.Entities.AppConfigInstance>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Xyz.Xrm.Entities.AppConfigMaster"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Xyz.Xrm.Entities.AppConfigMaster> AppConfigMasterSet
		{
			get
			{
				return this.CreateQuery<Xyz.Xrm.Entities.AppConfigMaster>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Xyz.Xrm.Entities.ApplicationFile"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Xyz.Xrm.Entities.ApplicationFile> ApplicationFileSet
		{
			get
			{
				return this.CreateQuery<Xyz.Xrm.Entities.ApplicationFile>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Xyz.Xrm.Entities.Appointment"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Xyz.Xrm.Entities.Appointment> AppointmentSet
		{
			get
			{
				return this.CreateQuery<Xyz.Xrm.Entities.Appointment>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Xyz.Xrm.Entities.AsyncOperation"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Xyz.Xrm.Entities.AsyncOperation> AsyncOperationSet
		{
			get
			{
				return this.CreateQuery<Xyz.Xrm.Entities.AsyncOperation>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Xyz.Xrm.Entities.Attachment"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Xyz.Xrm.Entities.Attachment> AttachmentSet
		{
			get
			{
				return this.CreateQuery<Xyz.Xrm.Entities.Attachment>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Xyz.Xrm.Entities.Attribute"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Xyz.Xrm.Entities.Attribute> AttributeSet
		{
			get
			{
				return this.CreateQuery<Xyz.Xrm.Entities.Attribute>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Xyz.Xrm.Entities.AttributeMap"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Xyz.Xrm.Entities.AttributeMap> AttributeMapSet
		{
			get
			{
				return this.CreateQuery<Xyz.Xrm.Entities.AttributeMap>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Xyz.Xrm.Entities.BusinessUnit"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Xyz.Xrm.Entities.BusinessUnit> BusinessUnitSet
		{
			get
			{
				return this.CreateQuery<Xyz.Xrm.Entities.BusinessUnit>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Xyz.Xrm.Entities.CanvasApp"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Xyz.Xrm.Entities.CanvasApp> CanvasAppSet
		{
			get
			{
				return this.CreateQuery<Xyz.Xrm.Entities.CanvasApp>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Xyz.Xrm.Entities.Contact"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Xyz.Xrm.Entities.Contact> ContactSet
		{
			get
			{
				return this.CreateQuery<Xyz.Xrm.Entities.Contact>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Xyz.Xrm.Entities.Email"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Xyz.Xrm.Entities.Email> EmailSet
		{
			get
			{
				return this.CreateQuery<Xyz.Xrm.Entities.Email>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Xyz.Xrm.Entities.Organization"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Xyz.Xrm.Entities.Organization> OrganizationSet
		{
			get
			{
				return this.CreateQuery<Xyz.Xrm.Entities.Organization>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Xyz.Xrm.Entities.PhoneCall"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Xyz.Xrm.Entities.PhoneCall> PhoneCallSet
		{
			get
			{
				return this.CreateQuery<Xyz.Xrm.Entities.PhoneCall>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Xyz.Xrm.Entities.PluginAssembly"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Xyz.Xrm.Entities.PluginAssembly> PluginAssemblySet
		{
			get
			{
				return this.CreateQuery<Xyz.Xrm.Entities.PluginAssembly>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Xyz.Xrm.Entities.PluginTraceLog"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Xyz.Xrm.Entities.PluginTraceLog> PluginTraceLogSet
		{
			get
			{
				return this.CreateQuery<Xyz.Xrm.Entities.PluginTraceLog>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Xyz.Xrm.Entities.PluginType"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Xyz.Xrm.Entities.PluginType> PluginTypeSet
		{
			get
			{
				return this.CreateQuery<Xyz.Xrm.Entities.PluginType>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Xyz.Xrm.Entities.PluginTypeStatistic"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Xyz.Xrm.Entities.PluginTypeStatistic> PluginTypeStatisticSet
		{
			get
			{
				return this.CreateQuery<Xyz.Xrm.Entities.PluginTypeStatistic>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Xyz.Xrm.Entities.Privilege"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Xyz.Xrm.Entities.Privilege> PrivilegeSet
		{
			get
			{
				return this.CreateQuery<Xyz.Xrm.Entities.Privilege>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Xyz.Xrm.Entities.ProcessSession"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Xyz.Xrm.Entities.ProcessSession> ProcessSessionSet
		{
			get
			{
				return this.CreateQuery<Xyz.Xrm.Entities.ProcessSession>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Xyz.Xrm.Entities.ProcessStage"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Xyz.Xrm.Entities.ProcessStage> ProcessStageSet
		{
			get
			{
				return this.CreateQuery<Xyz.Xrm.Entities.ProcessStage>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Xyz.Xrm.Entities.ProcessStageParameter"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Xyz.Xrm.Entities.ProcessStageParameter> ProcessStageParameterSet
		{
			get
			{
				return this.CreateQuery<Xyz.Xrm.Entities.ProcessStageParameter>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Xyz.Xrm.Entities.ProcessTrigger"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Xyz.Xrm.Entities.ProcessTrigger> ProcessTriggerSet
		{
			get
			{
				return this.CreateQuery<Xyz.Xrm.Entities.ProcessTrigger>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Xyz.Xrm.Entities.Queue"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Xyz.Xrm.Entities.Queue> QueueSet
		{
			get
			{
				return this.CreateQuery<Xyz.Xrm.Entities.Queue>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Xyz.Xrm.Entities.QueueItem"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Xyz.Xrm.Entities.QueueItem> QueueItemSet
		{
			get
			{
				return this.CreateQuery<Xyz.Xrm.Entities.QueueItem>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Xyz.Xrm.Entities.QueueItemCount"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Xyz.Xrm.Entities.QueueItemCount> QueueItemCountSet
		{
			get
			{
				return this.CreateQuery<Xyz.Xrm.Entities.QueueItemCount>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Xyz.Xrm.Entities.QueueMemberCount"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Xyz.Xrm.Entities.QueueMemberCount> QueueMemberCountSet
		{
			get
			{
				return this.CreateQuery<Xyz.Xrm.Entities.QueueMemberCount>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Xyz.Xrm.Entities.RibbonCustomization"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Xyz.Xrm.Entities.RibbonCustomization> RibbonCustomizationSet
		{
			get
			{
				return this.CreateQuery<Xyz.Xrm.Entities.RibbonCustomization>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Xyz.Xrm.Entities.Role"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Xyz.Xrm.Entities.Role> RoleSet
		{
			get
			{
				return this.CreateQuery<Xyz.Xrm.Entities.Role>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Xyz.Xrm.Entities.RolePrivileges"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Xyz.Xrm.Entities.RolePrivileges> RolePrivilegesSet
		{
			get
			{
				return this.CreateQuery<Xyz.Xrm.Entities.RolePrivileges>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Xyz.Xrm.Entities.SystemUser"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Xyz.Xrm.Entities.SystemUser> SystemUserSet
		{
			get
			{
				return this.CreateQuery<Xyz.Xrm.Entities.SystemUser>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Xyz.Xrm.Entities.SystemUserRoles"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Xyz.Xrm.Entities.SystemUserRoles> SystemUserRolesSet
		{
			get
			{
				return this.CreateQuery<Xyz.Xrm.Entities.SystemUserRoles>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Xyz.Xrm.Entities.Task"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Xyz.Xrm.Entities.Task> TaskSet
		{
			get
			{
				return this.CreateQuery<Xyz.Xrm.Entities.Task>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Xyz.Xrm.Entities.Team"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Xyz.Xrm.Entities.Team> TeamSet
		{
			get
			{
				return this.CreateQuery<Xyz.Xrm.Entities.Team>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Xyz.Xrm.Entities.TeamMembership"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Xyz.Xrm.Entities.TeamMembership> TeamMembershipSet
		{
			get
			{
				return this.CreateQuery<Xyz.Xrm.Entities.TeamMembership>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Xyz.Xrm.Entities.TeamRoles"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Xyz.Xrm.Entities.TeamRoles> TeamRolesSet
		{
			get
			{
				return this.CreateQuery<Xyz.Xrm.Entities.TeamRoles>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Xyz.Xrm.Entities.TransactionCurrency"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Xyz.Xrm.Entities.TransactionCurrency> TransactionCurrencySet
		{
			get
			{
				return this.CreateQuery<Xyz.Xrm.Entities.TransactionCurrency>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Xyz.Xrm.Entities.Workflow"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Xyz.Xrm.Entities.Workflow> WorkflowSet
		{
			get
			{
				return this.CreateQuery<Xyz.Xrm.Entities.Workflow>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Xyz.Xrm.Entities.WorkflowLog"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Xyz.Xrm.Entities.WorkflowLog> WorkflowLogSet
		{
			get
			{
				return this.CreateQuery<Xyz.Xrm.Entities.WorkflowLog>();
			}
		}
	}
	
	/// <summary>
	/// Attribute to handle storing the OptionSet's Metadata.
	/// </summary>
	[System.AttributeUsageAttribute(System.AttributeTargets.Field)]
	public sealed class OptionSetMetadataAttribute : System.Attribute
	{
		
		private object[] _nameObjects;
		
		private System.Collections.Generic.Dictionary<int, string> _names;
		
		/// <summary>
		/// Color of the OptionSetValue.
		/// </summary>
		public string Color { get; set; }
		
		/// <summary>
		/// Description of the OptionSetValue.
		/// </summary>
		public string Description { get; set; }
		
		/// <summary>
		/// Display order index of the OptionSetValue.
		/// </summary>
		public int DisplayIndex { get; set; }
		
		/// <summary>
		/// External value of the OptionSetValue.
		/// </summary>
		public string ExternalValue { get; set; }
		
		/// <summary>
		/// Name of the OptionSetValue.
		/// </summary>
		public string Name { get; set; }
		
		/// <summary>
		/// Names of the OptionSetValue.
		/// </summary>
		public System.Collections.Generic.Dictionary<int, string> Names
		{
			get
			{
				return _names ?? (_names = CreateNames());
			} 
			set
			{
				_names = value;
				if (value == null)
				{
				    _nameObjects = new object[0];
				}
				else
				{
				    _nameObjects = null;
				}
			}
		}
		
		/// <summary>
		/// Initializes a new instance of the <see cref="OptionSetMetadataAttribute"/> class.
		/// </summary>
		/// <param name="name">Name of the value.</param>
		/// <param name="displayIndex">Display order index of the value.</param>
		/// <param name="color">Color of the value.</param>
		/// <param name="description">Description of the value.</param>
		/// <param name="externalValue">External value of the value.</param>
		/// <param name="names">Names of the value.</param>
		public OptionSetMetadataAttribute(string name, int displayIndex, string color = null, string description = null, string externalValue = null, params object[] names)
		{
			this.Color = color;
			this.Description = description;
			this._nameObjects = names;
			this.ExternalValue = externalValue;
			this.DisplayIndex = displayIndex;
			this.Name = name;
		}
		
		private System.Collections.Generic.Dictionary<int, string> CreateNames()
		{
			System.Collections.Generic.Dictionary<int, string> names = new System.Collections.Generic.Dictionary<int, string>();
			for (int i = 0; (i < _nameObjects.Length); i = (i + 2))
			{
				names.Add(((int)(_nameObjects[i])), ((string)(_nameObjects[(i + 1)])));
			}
			return names;
		}
	}
	
	/// <summary>
	/// Extension class to handle retrieving of OptionSetMetadataAttribute.
	/// </summary>
	public static class OptionSetExtension
	{
		
		/// <summary>
		/// Returns the OptionSetMetadataAttribute for the given enum value
		/// </summary>
		/// <typeparam name="T">OptionSet Enum Type</typeparam>
		/// <param name="value">Enum Value with OptionSetMetadataAttribute</param>
		public static OptionSetMetadataAttribute GetMetadata<T>(this T value)
			where T :  struct, System.IConvertible
		{
			System.Type enumType = typeof(T);
			if (!enumType.IsEnum)
			{
				throw new System.ArgumentException("T must be an enum!");
			}
			System.Reflection.MemberInfo[] members = enumType.GetMember(value.ToString());
			for (int i = 0; (i < members.Length); i++
			)
			{
				System.Attribute attribute = System.Reflection.CustomAttributeExtensions.GetCustomAttribute(members[i], typeof(OptionSetMetadataAttribute));
				if (attribute != null)
				{
					return ((OptionSetMetadataAttribute)(attribute));
				}
			}
			throw new System.ArgumentException("T must be an enum adorned with an OptionSetMetadataAttribute!");
		}
	}
}
#pragma warning restore CS1591
